### ISSUE TITLE
worker process exited on signal 11 (core dumped)

### ISSUE THREAD

**Issue by setkyar** [knyar/nginx-lua-prometheus#105] opened 2020-08-25 18:15 UTC
I am setting up this exporter on

OS - `Ubuntu`
OS Version - `20.04.1 LTS (Focal Fossa)`
Nginx Version - `nginx version: nginx/1.18.0`

The following is my `nginx -V` result

```
nginx version: nginx/1.18.0
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-Krlwq0/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_geoip_module=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-headers-more-filter --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-cache-purge --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-ndk --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-echo --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-fancyindex --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-geoip2 --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/nchan --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-lua --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/rtmp --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-uploadprogress --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/http-subs-filter --add-dynamic-module=/build/nginx-Krlwq0/nginx-1.18.0/debian/modules/ssl-ct
```

I am putting the following block to `nginx.conf`. (I just clone the repo to this directory `/etc/nginx/nginx-lua-prometheus/`)

```
lua_shared_dict prometheus_metrics 10M;
lua_package_path "/etc/nginx/nginx-lua-prometheus/?.lua;;";

init_worker_by_lua_block {
  prometheus = require("prometheus").init("prometheus_metrics")
  metric_requests = prometheus:counter(
    "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
  metric_latency = prometheus:histogram(
    "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
  metric_connections = prometheus:gauge(
    "nginx_http_connections", "Number of HTTP connections", {"state"})
}

log_by_lua_block {
  metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
  metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
}
```

And getting quite lots of following Nginx logs

```
2020/08/25 17:59:44 [alert] 153630#153630: worker process 154357 exited on signal 11 (core dumped)
2020/08/25 17:59:44 [alert] 153630#153630: worker process 154359 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154361 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154363 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154365 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154367 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154369 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154371 exited on signal 11 (core dumped)
2020/08/25 17:59:45 [alert] 153630#153630: worker process 154373 exited on signal 11 (core dumped
```

The following is my full `nginx.conf`

```
http {
	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	# server_tokens off;

	server_names_hash_bucket_size 128;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;

	lua_shared_dict prometheus_metrics 10M;
        lua_package_path "/etc/nginx/nginx-lua-prometheus/?.lua;;";

        init_worker_by_lua_block {
                prometheus = require("prometheus").init("prometheus_metrics")
                metric_requests = prometheus:counter(
                        "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
                        metric_latency = prometheus:histogram(
                                "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
                                metric_connections = prometheus:gauge(
                                        "nginx_http_connections", "Number of HTTP connections", {"state"})
                }

        log_by_lua_block {
                metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
                metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
        }
}
```

I have an existing web application with the https setup. Do I miss something to configure?

**Comment by knyar** [comment] 2020-08-25 20:53
Are you sure this is related to this library? If you can prepare a `Dockerfile` that would reproduce this issue in a Docker container, I'd be happy to take a look and help you troubleshoot this.

**Comment by cableman** [comment] 2020-08-27 13:08
I see the same result, with the same version as above:
```
2020/08/27 15:07:21 [alert] 80146#80146: worker process 82995 exited on signal 11 (core dumped)
2020/08/27 15:07:21 [alert] 80146#80146: worker process 82997 exited on signal 11 (core dumped)
2020/08/27 15:07:22 [alert] 80146#80146: worker process 82999 exited on signal 11 (core dumped)
```
Followed the description given in the readme. If I remove the coded added to nginx.conf... it stops and nginx works as normal.

**Comment by eknoes** [comment] 2020-08-30 17:36
I experience the same problem with Ubuntu 20.04 but didn't experience it with Ubuntu 18.04. Changing the Dockerfiles `FROM` to `ubuntu:focal` reproduces this issue: The test can't reach the server and a `docker exec $IMAGE cat /var/log/nginx/error.log` shows the `core dumped` error.

**Comment by knyar** [comment] 2020-08-30 19:14
Thanks @eknoes, that's good to know. I have modified the `Dockerfile` from our integration test and could reproduce this in a docker container.

Looking at the core dump:
```
$ gdb /usr/sbin/nginx /tmp/core
[dd]
#0  0x00005597c1f6f63a in ?? ()
(gdb) bt
#0  0x00005597c1f6f63a in ?? ()
#1  0x00007f7ebec7be9c in ngx_http_lua_init_worker () from /usr/share/nginx/modules/ngx_http_lua_module.so
#2  0x00005597c1f5dd56 in ?? ()
#3  0x00005597c1f5e24f in ?? ()
#4  0x00005597c1f5c6c8 in ngx_spawn_process ()
#5  0x00005597c1f5f89f in ngx_master_process_cycle ()
#6  0x00005597c1f3144a in main ()
```

So it crashed in `ngx_http_lua_init_worker`. https://github.com/openresty/lua-nginx-module/issues/1714 reports a similar issue, so it does not look like it's a problem with this library.

Looking closer at what Ubuntu 20.04 ships with:
```
# dpkg -l | grep nginx
ii  libnginx-mod-http-echo     1.18.0-0ubuntu1            amd64        Bring echo and more shell style goodies to Nginx
ii  libnginx-mod-http-lua      1.18.0-0ubuntu1            amd64        Lua module for Nginx
ii  libnginx-mod-http-ndk      1.18.0-0ubuntu1            amd64        Nginx Development Kit module
ii  nginx-common               1.18.0-0ubuntu1            all          small, powerful, scalable web/proxy server - common files
ii  nginx-light                1.18.0-0ubuntu1            amd64        nginx web/proxy server (basic version)
# nginx -V 2>&1 | head -1
nginx version: nginx/1.18.0 (Ubuntu)
# cat /nginx-lua-prometheus/integration/print-version.conf
include /etc/nginx/modules-enabled/*.conf;
events {}

http {
    server {
        listen 18001;
        location / {
            content_by_lua_block {
                ngx.say(ngx.config.ngx_lua_version)
            }
        }
    }
}
# nginx -c /nginx-lua-prometheus/integration/print-version.conf
# curl localhost:18001
10011
#
```

So they package lua-nginx-module [version v0.10.11](https://github.com/openresty/lua-nginx-module/blob/ba2b60593010ad5d552a84f3c3ad3352f232d63d/src/api/ngx_http_lua_api.h#L22) with nginx 1.18.0. Looking at the [compatibility documentation](https://github.com/openresty/lua-nginx-module/tree/v0.10.11#nginx-compatibility) for lua-nginx-module v0.10.11, the last supported/tested version of nginx core is 1.13.6.

I strongly suspect that the issue is caused by the version of lua-nginx-module being too old and incompatible with nginx 1.18 in some way.

Perhaps Ubuntu maintainers forgot to update the `lua-nginx-module` while packaging nginx 1.18?

**Comment by eknoes** [comment] 2020-09-01 09:22
I just tried downgrading to nginx 1.17 as its also available on ubuntu 20.04, but this doesn't help either. I opened a bug report on Launchpad: https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1893753

**Comment by zevarito** [comment] 2021-02-24 17:50
Has someone found any solution or workaround to this issue?

**Comment by knyar** [comment] 2021-02-24 18:41
> Has someone found any solution or workaround to this issue?

Upgrading lua-nginx-module to 0.10.15 seems to be the easiest fix. I have [shared patches](https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1893753/comments/2) for hirsuite and focal ubuntu nginx packages that do that.

I am not seeing much enthusiasm to get those patches merged on the corresponding [ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1893753), but perhaps folks who use Ubuntu professionally and have a commercial relationship with Canonical might have some behind-the-scenes ways to get this fixed?

**Comment by zevarito** [comment] 2021-02-24 20:20
@knyar thank you very much for the update I'll check it out.

**Comment by amir860** [comment] 2021-05-12 17:46
@knyar can you explain how to upgrade lua-nginx-module to 0.10.15 ? How can i use those patches ? 
Thanks.

**Comment by amir860** [comment] 2021-05-12 17:49
> @knyar thank you very much for the update I'll check it out.

@zevarito can you help me to upgrade lua-nginx-module to 0.10.15 ?

**Comment by foozmeat** [comment] 2021-05-24 22:58
Ubuntu has decided to drop lua-nginx-module going forward

https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1893753/comments/8

**Comment by 1stdevfriend** [comment] 2022-01-13 17:54
Leaving this and trying to find other exporters just because of this.

**Comment by knyar** [comment] 2022-01-13 22:49
Not much else I can do here, I think, so closing this issue.

**Closed as completed** 2022-01-13 22:48 UTC
