### ISSUE TITLE
overhead

### ISSUE THREAD

**Issue by behnambm** [knyar/nginx-lua-prometheus#128] opened 2021-09-29 19:45 UTC
When i add the configs to `nginx.conf` and start nginx It uses 100% of CPU.

**Comment by knyar** [comment] 2021-09-30 08:14
Thank you for filing an issue. Unfortunately I am going to have to close it, because it's not really clear that the behaviour you are seeing is caused by this library. If you think you have discovered a bug in the library, please feel free to submit a PR with a fix, or at least a detailed description of the bug along with the steps necessary to reproduce it.

**Closed as completed by knyar** 2021-09-30 08:14 UTC
